services:
  - type: web
    name: retailmind-backend
    env: python
    buildCommand: pip install -r requirements.txt && python -m alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: "http://localhost:5173,https://retailmind-zalulus-projects.vercel.app,https://frontend-zalulus-projects.vercel.app,https://frontend-q0dbcxdvl-zalulus-projects.vercel.app,https://frontend-6ftn5a8py-zalulus-projects.vercel.app"
