"""add_rows_total_duplicates_skipped_to_upload_history

Revision ID: baf0f2c715d3
Revises: c3ce3f223289
Create Date: 2026-06-07 21:03:09.206535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baf0f2c715d3'
down_revision: Union[str, Sequence[str], None] = 'c3ce3f223289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_index(op.f('idx_user_category_month'), table_name='budgets')
    op.drop_table('budgets')
    op.create_index(op.f('ix_sale_records_upload_id'), 'sale_records', ['upload_id'], unique=False)
    op.add_column('upload_history', sa.Column('rows_total', sa.Integer(), nullable=True))
    op.add_column('upload_history', sa.Column('duplicates_skipped', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_history', 'duplicates_skipped')
    op.drop_column('upload_history', 'rows_total')
    op.drop_index(op.f('ix_sale_records_upload_id'), table_name='sale_records')
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('monthly_limit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('month', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('budgets_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('budgets_pkey'))
    )
    op.create_index(op.f('idx_user_category_month'), 'budgets', ['user_id', 'category', 'month'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('intelligence_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by_ai', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('transactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    # ### end Alembic commands ###
