"""add_anomaly_snapshot_to_audits

Revision ID: dd8a2e7ceaae
Revises: baf0f2c715d3
Create Date: 2026-06-07 21:13:37.034310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd8a2e7ceaae'
down_revision: Union[str, Sequence[str], None] = 'baf0f2c715d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('anomaly_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'anomaly_snapshot')
    # ### end Alembic commands ###
